# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  containers:
  - container: fortify
    image: s00271sacrdevops.azurecr.io/gas/fortify:18.20
    endpoint: s00271sacrdevops.azurecr.io

jobs:
- job: build
  timeoutInMinutes: 10
  container: fortify
  steps:
    - script: echo Hello World
